### PR TITLE
Disassembler

### PR DESCRIPTION
**Pull request by freistof**
I fixed the Norm errors. I also started writing comments.
There are norm errors in the print function but I still need it and we will not hand that in.

### CODE REVIEW

**Comment by sandriches** [comment]
- [ ] No arguments after the last operation works where it should not

**Comment by sandriches** [comment]
- [ ] '-' on its own works (as an indirect value)
- [ ] naughty sweary error message for '%' (as a direct value) also for label that doesn't exist
- [ ] Commas need to be looked at. '[instruction],[only_argument]'; '%100,'; ',%10'; ',,,,,,%10' and '%100,,,,' all accepted (direct)
- [ ] 'live\n', 'ld\n',  works (without arg)
- [ ] instructions all work with double last letter eg livee, stii, ldd
- [ ] ';' comments still don't work
- [ ] label when whitespace beforehand doesn't assemble

**Comment by freistof** [comment]
- [ ] In the visualizer: when the comment or name is more than one line it does not display properly
- [ ] Add introduction (see original Core War)
- [ ] If the champion is too small to be a champion, the program just displays usage - I think it should display a proper error message when that is the case
- [ ] The same is true for the situation where the exec_code is not the same as size says
- [ ] And the same is true for when I put values in the 4 bytes that are supposed to be NULL
- [ ] The same is true for when I mess with the magic header
- [ ] Or when I put more than 4 champions (maybe add that to usage)
- [ ] Would be nice to see the current delay in the visualizer
- [ ] Some clarity as to whether it is visualiser or visualizer
- [ ] If two .cor files have the same name and are playing against each other, it would be good to specify which player number has won instead of the player name

**Comment by freistof** [comment]
make re

**Comment by freistof** [comment]
Hello boys, my work is ready for moar testing

**Pull request merged**
